### ISSUE TITLE
atualizar aba de equipe

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_site#12]
Ja fiz as devidas edições nos arquivos dos novos membros de equipe e ja subi para o repo. Agora só precisa ajustar o layout da pagina para aparecer todo mundo.

**Comment by kauebraga** [comment]
Done at https://github.com/ipeaGIT/acesso_site/commit/001d63e7392c7144d0168a7263a1c388b253882f :)
