### ISSUE TITLE
add icon of social protection

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_site#21]
Peguei o codigo do icone [daqui](https://fontawesome.com/icons/hands-holding-circle?s=solid&f=classic). Se eu simplesmente adicionar uma quarta linha repetindo o icone de saude, por exemplo, o site mostra o quarto icone. Mas por algum motivo o icone com as mãos nao aparece de jeito nenhum. [Aqui no repositorio o arquivo com o codiogo atualizado, mas q nao mostra o icone novo](https://github.com/ipeaGIT/acesso_site/blob/master/content/pt/sobre/2-escopo.md).

@kauebraga , tu tem ideia de como resolver isso?

Cc @dhersz

**Comment by kauebraga** [comment]
Hm, não atualizou nada do código, inclusive o item (print do código no site)
![image](https://user-images.githubusercontent.com/22420248/199578018-ee252c39-d8fa-4b39-9277-8c82446947e7.png)

Muito provável que o problema é no deploy

**Comment by kauebraga** [comment]
Eu fiz um novo release, mas tem que dar um deploy no jenkins né?

**Comment by kauebraga** [comment]
Esse novo ícone é de uma versão mais recente do font awesome, que não é a default do hugo/blogdown.
Adicionei o código pra puxar a versão mais recente aqui 1a9ff754f1ea4a88cf20648353c066d65dac9b67

![image](https://user-images.githubusercontent.com/22420248/199582062-f386895d-067a-4da7-8bd8-9e26fc159bf4.png)

**Comment by rafapereirabr** [comment]
valeu
