### ISSUE TITLE
Wrong tab name while accessing different sections

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_site#24]
When I am accessing the ['Software' section on the english version](https://www.ipea.gov.br/acessooportunidades/en/software/), the tab name on the top names it as "O Projeto | ...". 
This issue is also happening in the pt-br "Software: section and with the "Sobre" pt-br section. 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/c3b3ba06-1228-4724-8cd2-6a3e789caf62">

**Comment by rafapereirabr** [comment]
valeu! acabei de corrigir isso com o commit anterior. Isso vai ficar corrigido no proximo deploy. Ainda nao fiz novo deploy pq estou esperando fazer mais algumas mudanças no site muito em breve. Dai faço uma atualização só.
thanks !
